source "https://rubygems.org"

# ------
#   Sinatra-React-Webpack emplate
# ------


# ------
#   For loupe
# ------

gem "gems"
gem "json"

# ------
#   For Development
# ------

group :development do
  gem "guard"
  gem "guard-livereload", "~> 2.5", require: false
  gem "rack-livereload"
  gem "rubocop", require: false
end
